title: Ganesh Annapa
logo: docs/assets/Headshot.jpg
description: Application Programmer Analyst | Visual Enthusiast | Data Science
emails:
  - "ganeshreddya151@gmail.com"
  - "annapaganeshreddy@gmail.com"
website: "https://www.ganeshreddy.com"
theme: jekyll-theme-minimal
